### ISSUE TITLE
Make Palm Icon gray

### ISSUE THREAD

**Issue by obstschale** [obstschale/child-page-tree#2]
== In Backend ==

Add this style to make the palm icon as gray as the other icons.

``` css
.dashicons-palmtree:before {
    content: "\f527";
    color: #82878c; /* add color so it fits the other dashicons */
}
```
